options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/recipiz-457601/recipiz-repo/recipiz', '.']
    timeout: 1200s

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/recipiz-457601/recipiz-repo/recipiz']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'recipiz',
        '--image',
        'us-central1-docker.pkg.dev/recipiz-457601/recipiz-repo/recipiz',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--port',
        '3000',
        '--set-secrets',
        'POSTGRES_URL=POSTGRES_URL:latest',
        '--set-secrets',
        'NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest',
        '--set-secrets',
        'NEXTAUTH_URL=NEXTAUTH_URL:latest',
        '--set-secrets',
        'CLOUDINARY_CLOUD_NAME=CLOUDINARY_CLOUD_NAME:latest',
        '--set-secrets',
        'CLOUDINARY_API_KEY=CLOUDINARY_API_KEY:latest',
        '--set-secrets',
        'CLOUDINARY_API_SECRET=CLOUDINARY_API_SECRET:latest',
        '--set-secrets',
        'NEXT_PUBLIC_SUPABASE_URL=NEXT_PUBLIC_SUPABASE_URL:latest',
        '--set-secrets',
        'NEXT_PUBLIC_SUPABASE_ANON_KEY=NEXT_PUBLIC_SUPABASE_ANON_KEY:latest',
        '--set-secrets',
        'RAW_TEXT_EXTRACTOR_API_URL=RAW_TEXT_EXTRACTOR_API_URL:latest',
        '--set-secrets',
        'OPENAI_API_KEY=OPENAI_API_KEY:latest',
      ]
